---
- name: this action perform on local
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update package cache
    apt:
      update_cache: yes

  - name: Install dependencies
    apt:
      name:
        - libasound2
        - libatk1.0-0
        - libc6
        - libcairo2
        - libcups2
        - libdbus-1-3
        - libexpat1
        - libfontconfig1
        - libgcc1
        - libgconf-2-4
        - libgdk-pixbuf2.0-0
        - libglib2.0-0
      state: present

#  - name: Download Microsoft Teams package
#    command: wget -P /tmp/teams.deb https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb
  - name: Download Microsoft Teams package
    uri:
      url: https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb
      dest: /tmp/teams.deb

  - name: Install Microsoft Teams
    apt:
      deb: /tmp/teams.deb
      state: present
...
